apiVersion: kremser.dev/v1
kind: RbacNegotiation
metadata:
  name: for-k8gb-using-deployment
spec:
  for:
    kind: Deployment
    name: k8gb
  role:
    name: new-k8gb-role
    isClusterRole: true
    createIfNotExist: true

