---
apiVersion: kremser.dev/v1
kind: RbacNegotiation
metadata:
  name: for-prom-deploy
spec:
  for:
    kind: Deployment
    name: prometheus-operator
  role:
    name: custom-monitoring-role2
    isClusterRole: false
    createIfNotExist: true
---
