---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
---
apiVersion: kremser.dev/v1
kind: RbacNegotiation
metadata:
  name: for-prom-svc
spec:
  for:
    kind: Service
    name: prometheus-operator-svc
  serviceAccountName: prometheus-operator
  role:
    name: custom-monitoring-role1
    isClusterRole: true
    createIfNotExist: true
---
