project_name: log2rbac
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: ./bin/log2rbac
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }} -X main.gitSha={{ .Commit }}
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"
dockers:
  - image_templates:
      - "docker.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-amd64"
      - "gcr.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
  - image_templates:
      - "docker.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-arm64"
      - "gcr.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-arm64"
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
docker_manifests:
  - name_template: docker.io/jkremser/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - docker.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-amd64
      - docker.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-arm64
  - name_template: gcr.io/jkremser/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - gcr.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-amd64
      - gcr.io/jkremser/{{ .ProjectName }}:v{{ .Version }}-arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"
release:
  draft: true
