resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: Deployment
images:
- name: jkremser/log2rbac
  newName: jkremser/log2rbac
  newTag: latest
- name: jkremser/log2rbac:latest
  newName: jkremser/log2rbac
  newTag: latest

