# permissions for end users to edit rbacnegotiations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbacnegotiation-editor-role
rules:
- apiGroups:
  - kremser.dev
  resources:
  - rbacnegotiations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kremser.dev
  resources:
  - rbacnegotiations/status
  verbs:
  - get

