apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  ports:
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: dashboard
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: jaeger-health
      port: 13133
      protocol: TCP
      targetPort: 13133
    - name: http-collector
      port: 14250
      protocol: TCP
      targetPort: 14250
  selector:
    id: log2rbac
  type: ClusterIP
