apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: dashboard
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: jaeger-health
      port: 13133
      protocol: TCP
      targetPort: 13133
    - name: http-collector
      port: 14250
      protocol: TCP
      targetPort: 14250
  selector:
    id: jaeger
  type: ClusterIP
