# This patch injects a sidecar container which is a open telemetry collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log2rbac
  namespace: log2rbac
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          - name: TRACING_ENABLED
            value: "true"
#      - name: jaeger
#        image: jaegertracing/opentelemetry-all-in-one
      - name: otel-collector
        image: otel/opentelemetry-collector:0.48.0
        args:
          - --config=/conf/agent.yaml
        volumeMounts:
          - mountPath: /conf
            name: agent-config
      volumes:
        - configMap:
            items:
              - key: agent.yaml
                path: agent.yaml
            name: agent-config
          name: agent-config
