# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rbacnegotiations.kremser.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: log2rbac
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1

