apiVersion: kremser.dev/v1
kind: RbacNegotiation
metadata:
  name: rbacnegotiation-sample
spec:
  for:
    namespace: default
    kind: Deployment
    name: test-echo
  role:
    name: new-role
    isClusterRole: true
    createIfNotExist: true
