{{- if .Values.deploy.operator }}
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    control-plane: log2rbac
  name: log2rbac
  namespace: log2rbac
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: log2rbac
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        control-plane: log2rbac
        id: log2rbac
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        name: manager
        command:
        - /log2rbac
        args:
        - --health-probe-bind-address=:8081
        - --zap-encoder=console
        - --leader-elect
        {{- if .Values.metrics.enabled }}
        - --metrics-bind-address=127.0.0.1:{{ .Values.metrics.port }}
        {{- end }}
        env:
        {{- with .Values.operator }}
        - name: COLORS
          value: {{ .colors | quote }}
        - name: NO_BANNER
          value: {{ .noBanner | quote }}
        - name: SHOULD_RESTART_APP_PODS
          value: {{ .restartPods | quote }}
          {{- with .syncIntervals }}
        - name: SYNC_INTERVAL_AFTER_NO_RBAC_ENTRY_MINUTES
          value: {{ .afterNoRbacEntry | quote }}
        - name: SYNC_INTERVAL_AFTER_NO_LOGS_SECONDS
          value: {{ .afterNoLogs | quote }}
        - name: SYNC_INTERVAL_AFTER_POD_RESTART_SECONDS
          value: {{ .afterPodRestart | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.tracing.enabled }}
          {{- with .Values.tracing }}
        - name: TRACING_ENABLED
          value: {{ .enabled | quote }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .endpoint | quote }}
            {{- with .samplingRatio }}
        - name: TRACING_SAMPLING_RATIO
          value: {{ . | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      {{- if .Values.tracing.enabled }}
      - image: {{ .Values.tracing.sidecarImage.repository }}:{{ .Values.tracing.sidecarImage.tag }}
        name: otel-collector
        args:
        - --config=/conf/agent.yaml
        volumeMounts:
        - mountPath: /conf
          name: agent-config
      volumes:
      - configMap:
          items:
          - key: agent.yaml
            path: agent.yaml
          name: agent-config
        name: agent-config
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: log2rbac
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
