{{- if .Values.deploy.rbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log2rbac
  namespace: log2rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: log2rbac-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log2rbac-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log2rbac-role
subjects:
- kind: ServiceAccount
  name: log2rbac
  namespace: log2rbac
---
{{- end}}