{{- if .Values.deploy.service }}
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: log2rbac
  name: log2rbac-metrics
  namespace: log2rbac
spec:
  type: {{ .Values.metrics.serviceType }}
  ports:
  - name: http
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port }}
    {{- if eq .Values.metrics.serviceType "NodePort" }}
    nodePort: {{ .Values.metrics.nodePort }}
    {{- end }}
  selector:
    control-plane: log2rbac
{{- end }}
{{- end }}
