# thanks to https://github.com/giantswarm/devctl/blob/v5.9.0/pkg/gen/input/workflows/internal/file/check_values_schema.yaml.template for the idea

name: 'Check if values schema file has been updated'
on:
  pull_request:
    branches:
      - master
    paths:
      - 'helm-chart/log2rbac-operator/values.yaml'
      - 'helm-chart/log2rbac-operator/values.schema.json'
permissions:
  contents: read

jobs:
  check:
    name: 'Check values.yaml and its schema in PR'
    runs-on: ubuntu-20.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5565dcdcb788a76ec5c5ca1d7b54135c92b4db13
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: 'Checkout'
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: 'Check if values.schema.json was updated'
        run: |
          VALUES_FILE=helm-chart/log2rbac-operator/values.yaml
          SCHEMA_FILE=helm-chart/log2rbac-operator/values.schema.json

          # check if the values.json is covered by the schema
          pip3 install json-spec
          yq -o=json eval ${VALUES_FILE} > /tmp/values.json
          json validate --schema-file=${SCHEMA_FILE} --document-file=/tmp/values.json
          echo "PASSED: values.yaml and values.schema.json both appear to have been updated and the document is valid against the schema"
