name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  IMG: candidate
  GOLANG_VERSION: 1.19.1
  DOCKER_ORG: jkremser

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: Lint using golangci-lint
        uses: golangci/golangci-lint-action@v3.3.0
        with:
          args: --timeout=120s
          skip-cache: true

      - name: gokart
        run: |
          go install github.com/praetorian-inc/gokart@v0.5.1
          gokart scan --globalsTainted

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Build
        run: |
          go version
          make build

      - name: Test
        run: |
          curl -s https://gotest-release.s3.amazonaws.com/gotest_linux > gotest && chmod +x gotest
          ./gotest ./...

  e2e-on-k8s:
    name: e2e tests against kubernetes
    runs-on: ubuntu-20.04
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Install stuff
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          curl -s https://gotest-release.s3.amazonaws.com/gotest_linux > gotest && chmod +x gotest
          go get -u github.com/rakyll/gotest &> /dev/null

      - name: Login to Dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.DOCKER_ORG }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container image
        run: |
          make container-img

      - name: Spawn k8s cluster and import the image
        run: |
          k3d cluster create --no-lb --k3s-arg "--disable=traefik,servicelb,metrics-server,local-storage@server:*"
          echo "importing image: ${IMG}"
          k3d image import ${IMG}:latest
          echo "Kubernetes vesion:"
          kubectl version --short

      - name: Deploy the operator
        run: |
          make install deploy
          kubectl wait deploy/log2rbac -n log2rbac --for condition=available --timeout=2m && sleep 10

      - name: Test
        run: |
          cd e2e-test/ && ../gotest ./...

      - name: Push the :latest container image
        run: |
          docker tag ${IMG} docker.io/${DOCKER_ORG}/log2rbac:latest
          docker push docker.io/${DOCKER_ORG}/log2rbac:latest

      - name: Print test logs & debug
        if: always()
        run: |
          echo "::group::env | sort"
          env | sort
          echo "::endgroup::"

          echo "::group::k get events"
          kubectl get events -A || true
          echo "::endgroup::"

          echo "::group::k describe deploy log2rbac"
          kubectl describe deploy -nlog2rbac log2rbac || true
          echo "::endgroup::"

          echo "::group::k describe clusterrole new-k8gb-role"
          kubectl describe clusterrole new-k8gb-role || true
          echo "::endgroup::"

          echo -e "\n\nCRs:"
          kubectl get rn -A -owide || true
          echo -e "\n\n Deployments:"
          kubectl get deployment -A || true
          echo -e "\n\n Operator logs:"
          kubectl logs -nlog2rbac -lid=log2rbac --tail=200 || true

