name: CI
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  IMG: candidate

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: Lint using golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.1

      - name: gokart
        run: |
          go install github.com/praetorian-inc/gokart@v0.2.0
          gokart scan --globalsTainted

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Build
        run: |
          go version
          make build

      - name: Test
        run: |
          go get -u github.com/rakyll/gotest &> /dev/null
          gotest ./...

  e2e-on-k8s:
    name: e2e tests against kubernetes
    runs-on: ubuntu-20.04
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          go get -u github.com/rakyll/gotest &> /dev/null

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container image and import it to k3d
        run: |
          make container-img
          k3d image import $IMG

      - name: Spawn k8s cluster
        run: |
          k3d cluster create --no-lb --k3s-arg "--disable=traefik,servicelb,metrics-server,local-storage@server:*"

      - name: Deploy the operator
        run: |
          make install deploy
          kubectl wait deploy/log2rbac -n log2rbac --for condition=available && sleep 10

      - name: Test
        run: |
          cd e2e-test/ && go mod download && gotest ./...

      - name: Push the :latest container image
        run: |
          docker tag $IMG docker.io/jkremser/log2rbac:latest
          docker push docker.io/jkremser/log2rbac:latest
