name: CI
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  go-inspect:
    name: Lint and Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - run: |
          go version
          make build
      # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.1
      - name: gokart
        run: |
          go install github.com/praetorian-inc/gokart@v0.2.0
          gokart scan --globalsTainted
      - name: go test
        run: |
          go get -u github.com/rakyll/gotest
          gotest ./...