name: Helm Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 0
      - uses: dave-mcconnell/helm-gh-pages-microservices@master
        with:
          access-token: ${{ secrets.RELEASER_TOKEN }}
          source-charts-folder: 'helm-chart'
          destination-repo: jkremser/log2rbac-operator
          destination-branch: gh-pages
      - name: Invoke workflow for OLM
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7 # tag=v1
        with:
          workflow: OLM bundle and PR
          token: ${{ secrets.RELEASER_TOKEN }}
          inputs: '{ "bundleVersion": "master" }'
