name: Helm docs
on:
  push:
    branches:
    - 'main'
    paths:
     - 'helm-chart/log2rbac-operator/**'
permissions:
  contents: read

jobs:
  build-helm-doc:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update Helm Doc
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout Code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Generate docs for helm chart - helm-chart/log2rbac-operator/README.md
      uses: docker://jnorwood/helm-docs@sha256:7e562b49ab6b1dbc50c3da8f2dd6ffa8a5c6bba327b1c6335cc15ce29267979c
      with:
        args: --template-files=_helm-docs-template.gotmpl
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5
      with:
        title: "Update Helm Docs"
        branch: ci-helm-doc
        delete-branch: true
        base: main
        signoff: true
        token: ${{ secrets.GITHUB_TOKEN }}

