name: Helm docs
on:
  push:
    branches:
    - 'main'
    paths:
     - 'helm-chart/log2rbac-operator/**'
permissions:
  contents: read

jobs:
  build-helm-doc:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update Helm Doc
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout Code
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Generate docs for helm chart - helm-chart/log2rbac-operator/README.md
      uses: docker://jnorwood/helm-docs@sha256:7e562b49ab6b1dbc50c3da8f2dd6ffa8a5c6bba327b1c6335cc15ce29267979c
      with:
        args: --template-files=_helm-docs-template.gotmpl
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
      with:
        title: "Update Helm Docs"
        branch: ci-helm-doc
        delete-branch: true
        base: main
        signoff: true
        token: ${{ secrets.GITHUB_TOKEN }}

