name: Helm Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - uses: dave-mcconnell/helm-gh-pages-microservices@8478af5f0fd712cc0fb59f2c99e0688f3f591287 # tag=v1.5.0
        with:
          access-token: ${{ secrets.RELEASER_TOKEN }}
          source-charts-folder: 'helm-chart'
          destination-repo: jkremser/log2rbac-operator
          destination-branch: gh-pages
      - name: Invoke workflow for OLM
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1
        with:
          workflow: OLM bundle and PR
          token: ${{ secrets.RELEASER_TOKEN }}
          inputs: '{ "bundleVersion": "main" }'
