name: Helm docs
on:
  push:
    branches:
    - 'master'
    paths:
     - 'helm-chart/log2rbac-operator/**'
jobs:
  build-helm-doc:
    name: Update Helm Doc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Generate docs for helm chart - helm-chart/log2rbac-operator/README.md
      uses: docker://jnorwood/helm-docs:v1.11.0
      with:
        args: --template-files=_helm-docs-template.gotmpl
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # tag=v4
      with:
        title: "Update Helm Docs"
        branch: ci-helm-doc
        delete-branch: true
        base: master
        signoff: true
        token: ${{ secrets.GITHUB_TOKEN }}

