name: Helm docs
on:
  push:
    branches:
    - 'master'
    paths:
     - 'helm-chart/log2rbac-operator/**'
permissions:
  contents: read

jobs:
  build-helm-doc:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update Helm Doc
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # tag=v1.5.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout Code
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Generate docs for helm chart - helm-chart/log2rbac-operator/README.md
      uses: docker://jnorwood/helm-docs@sha256:66c8f4164dec860fa5c1528239c4aa826a12485305b7b224594b1a73f7e6879a
      with:
        args: --template-files=_helm-docs-template.gotmpl
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # tag=v4
      with:
        title: "Update Helm Docs"
        branch: ci-helm-doc
        delete-branch: true
        base: master
        signoff: true
        token: ${{ secrets.GITHUB_TOKEN }}

