name: OLM bundle and PR

on:
  workflow_dispatch:
    inputs:
      bundleVersion:
        description: Version of the bundle that should be generated. If not provided, the latest release tag is taken. Use 'main' for incorporating the latest changes in repo
        required: false
        default: ""
      upstreamRepo:
        description: "The pull request will be opened against this repository"
        required: true
        default: "k8s-operatorhub/community-operators"
      olmBundleToolVersion:
        description: "Version of the olm-bundle tool that generate CSV file from Chart.yaml and yamls on FS"
        required: false
        default: "0.5.4"

permissions:
  contents: read

jobs:
  olm-bundle-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event.inputs.bundleVersion }}x" == "x" ]; then
            version=$(git describe --abbrev=0 --tags)
          else
            version=${{ github.event.inputs.bundleVersion }}
          fi
          if [ "${{ github.event.inputs.bundleVersion }}" == "main" ]; then
            bundleDir=$(git describe --abbrev=0 --tags)
          else
            bundleDir=${version}
          fi
          echo "::set-output name=bundleDir::${bundleDir#v}"
          echo "::set-output name=version::${version#v}"

      - name: Generate OLM bundle
        env:
          TOOL_VERSION: ${{ github.event.inputs.olmBundleToolVersion }}
          DEBUG: 1
        run: |
          ./olm/generate.sh ${{ steps.get_version.outputs.version }}
          rm ./olm/bundle/Dockerfile
          cp -r ./olm/bundle $GITHUB_WORKSPACE/

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.inputs.upstreamRepo }}
          path: sandbox
          token: ${{ secrets.RELEASER_TOKEN }}
          fetch-depth: 0

      - name: Copy the generated manifests
        run: |
          mkdir -p $GITHUB_WORKSPACE/sandbox/operators/log2rbac/
          rm -rf $GITHUB_WORKSPACE/sandbox/operators/log2rbac/${{ steps.get_version.outputs.bundleDir }} || true
          cp -r $GITHUB_WORKSPACE/bundle/ $GITHUB_WORKSPACE/sandbox/operators/log2rbac/${{ steps.get_version.outputs.bundleDir }}

      - name: Open Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5
        with:
          token: ${{ secrets.RELEASER_TOKEN }}
          push-to-fork: jkremser/community-operators
          path: sandbox
          commit-message: OLM bundle for log2rbac@${{ steps.get_version.outputs.bundleDir }}
          title: operators log2rbac ({{ steps.get_version.outputs.bundleDir }})
          body: |
            :package: Update log2rbac operator bundle :package:

            ### New Submissions
            N/A

            ### Updates to existing Operators
            - [x] All checks

            ### Your submission should not
            - [x] All checks

            ### Operator Description must contain (in order)
            - [x] All checks

            ### Operator Metadata should contain
            - [x] All checks

            This automated PR was created by [this action][1].

            [1]: https://github.com/jkremser/log2rbac-operator/actions/runs/${{ github.run_id }}
          branch: log2rbac-${{ steps.get_version.outputs.bundleDir }}
          delete-branch: true
          signoff: true

      - name: Check PR
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
