name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tag
        id: get_tag
        run: |
          previous_tag=$(git tag --sort=v:refname | tail -2 | head -1)
          echo "::set-output name=previous_tag::${previous_tag}"

      - uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.RELEASER_TOKEN }}
          project: log2rbac-operator
          sinceTag: ${{ steps.get_tag.outputs.previous_tag }}
          output: changes
          pullRequests: true
          author: true
          issues: true
          issuesWoLabels: true
          prWoLabels: true
          compareLink: true
          filterByMilestone: true
          unreleased: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: v1.9.2
          args: release --rm-dist --release-notes=changes
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.12.1'

      - name: Sign with Cosign
        id: sign
        run: |
          ./hack/slsa/sign-image.sh ${{ github.ref_name }}
          digest=$(DIGEST_ONLY=true ./hack/slsa/sign-image.sh ${{ github.ref_name }})
          echo "::set-output name=digest::${digest}"

      - name: Generate SLSA Provenance
        uses: philips-labs/slsa-provenance-action@v0.8.0
        with:
          command: generate
          subcommand: container
          arguments: --digest ${{ steps.sign.outputs.digest }} --tags ${{ github.ref_name }}

      - name: Attach SLSA Provenance
        env:
          PROVENANCE: "true"
        run: |
          ./hack/slsa/sign-image.sh ${{ github.ref_name }}

      - name: Upload SLSA Provenance
        uses: actions/upload-artifact@v2
        with:
          path: provenance.json

      - name: Send http get to doc.crds.dev to index a new version
        run: |
          curl -sL https://doc.crds.dev/github.com/jkremser/log2rbac-operator@${{ github.ref_name }} | grep -A2 'class="container"'
